### PR TITLE
Works now with Podfile, Alamofire 3.5, Gloss 0.8 and Swift 2.3

### PR DESCRIPTION
**Pull request by jpunz**
Wasn't working for me in Swift 2.3, so i did some changes.

### CODE REVIEW

**Comment by spxrogers** [comment]
hi @jpunz! high level all looks good :) 
once I can get a chance to hop on and verify it all, I'll merge.

**Comment by jpunz** [comment]
It's okay.
Just used your library for my app and after updating to xcode 8, everything was broken. So i just tried to fix that for me and thought, it may be interesting for you too.

Regards,
Jürgen

**Comment by spxrogers** [comment]
oh of course! I really appreciate the community support :)

**Comment by jpunz** [comment]
I send you a new pull request, did a small fix

**Pull request closed without merging**
